### ISSUE TITLE
extracted sound from pcap is noise

### ISSUE THREAD

**Issue by energygreek** [Spinlogic/AMR-WB_extractor#3]
hello, this tool always works file and help me a lot, but not works on this pcap file and no error reported,  could you help find why? 

```
python pcap_parser.py -i /tmp/error5.pcap  -o output-err.amr -c amr-wb -f ietf  
```
[sound.zip](https://github.com/Spinlogic/AMR-WB_extractor/files/10382375/sound.zip)

**Comment by Spinlogic** [comment]
Are you sure that the payload is really AMR-WB or AMR? e.g. does the signalling show that AMR-WB is the selected codec?, 
Have you tried decoding manually some of the packets to verify that this is actually AMR-WB? , this checking can be done quickly with Wireshark, decoding the packets as RTP and matching the RTP payload against RFC4867.

**Comment by energygreek** [comment]
it's my fault, this tool is very helpful.
